config/routes.rb
TxtyourcityRails::Application.routes.draw do
  resources :groups
  resources :group_users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :registrations => "registrations" }, :path_names => { :sign_up => ENV['SIGN_UP_PATH'] || 'textizen4eva' }

  resources :polls do
    put :end, :on => :member # for polls/3/end?
    put :clear_responses, :on => :member # for polls/3/nuke
    collection do
      post "receive_message"
    end
  end

  resources :responses do
    collection do
      post "receive_message"
    end
  end

  match 'welcome' => 'static_pages#home'
  match 'about' => 'static_pages#about'
  match 'privacy' => 'static_pages#privacy'
  match 'getstarted' => 'static_pages#getstarted'

  root :to => 'application#index' #'polls#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are: :registerable
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # only allow signups on dev machines during the beta. TODO make this a config var, not hardcoded?

  if ENV['BLOCK_REGISTRATIONS'] == 'true'
    devise :async, :invitable, :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  else
    devise :async, :invitable, :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable 
  end

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role, :invitation_token
  # attr_accessible :title, :body
  has_many :created_polls, :class_name => "Poll", :foreign_key => "user_id"
  has_many :group_users
  has_many :groups, :through => :group_users
  has_many :polls, :through => :groups

  ROLES = %w[editor superadmin]
  validates :role, :inclusion => { :in => ROLES, :message => "%{value} is not a valid user role" }

  validates_uniqueness_of :email


  # for role inheritance
  def role?(base_role)
    unless role.nil?
      ROLES.index(base_role.to_s) <= ROLES.index(role)
    else
      false #if no role defined, default to always failing
    end
  end

  def visible_polls
    if role?(:superadmin)
      return Poll.all
    else
      return polls | created_polls #union of poll and created_polls for non admin users
    end
  end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_filter :authenticate_user!, :only => :index
  load_and_authorize_resource

  # GET /polls
  # GET /polls.json
  def index
    # TODO: transfer this to cancan syntax, eventually
    if can? :index, Poll
      if current_user.role?(:superadmin)
        @groups = Group.all
      else
        @groups = current_user.groups
      end

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @polls }
      end
    end
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @poll = Poll.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @poll }
      format.csv { export_to_csv }
    end
  end

  # GET /polls/new
  # GET /polls/new.json
  def new
    @poll = Poll.new(:end_date => Time.now + 2.months)
    if current_user.role?(:superadmin)
      @groups = Group.all
    else
      @groups = current_user.groups
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll }
    end
  end

  # GET /polls/1/edit
  def edit
    @editing = true
    @poll = Poll.find(params[:id])
    if current_user.role?(:superadmin)
      @groups = Group.all
    else
      @groups = current_user.groups
    end
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(params[:poll])
    @poll.author = current_user

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render json: @poll, status: :created, location: @poll }
      else
        if current_user.role?(:superadmin)
          @groups = Group.all
        else
          @groups = current_user.groups
        end
        puts @poll.errors.full_messages
        format.html { render action: "new" }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /polls/1
  # PUT /polls/1.json
  def update
    @poll = Poll.find(params[:id])

    respond_to do |format|
      if @poll.update_attributes(params[:poll])
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { head :no_content }
      else
        if current_user.role?(:superadmin)
          @groups = Group.all
        else
          @groups = current_user.groups
        end
        puts @poll.errors.full_messages
        format.html { render action: "edit" }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy

    respond_to do |format|
      format.html { redirect_to polls_url }
      format.json { head :no_content }
    end
  end

  # PUT /polls/1/end
  def end
    @poll = Poll.find(params[:id])

    respond_to do |format|
      if @poll.update_attributes({:end_date=> Time.now})
        format.html { redirect_to @poll, notice: 'Poll was successfully ended.' }
        format.json { head :no_content }
      else
        format.html { render action: "index" }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
    #flash[:notice] = "ended poll"
  end

  def clear_responses
    @poll = Poll.find(params[:id])

    respond_to do |format|
      if @poll.responses_all.each(&:destroy) # destroy all responses, including follow-ups
        format.html { redirect_to @poll, notice: 'Responses successfully cleared.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @poll, notice: 'Error clearing responses :(' }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  def export_to_csv
    send_data @poll.to_csv,
      :type => 'text/csv; charset=iso-8859-1; header=present',
      :disposition => "attachment; filename=poll#{@poll.id}.csv"
  end

  def publish
    @poll = Poll.find(params[:id])

    respond_to do |format|
      if @poll.update_attributes({:public=> !@poll.public})
        format.html { redirect_to @poll, notice: "Poll was successfully #{@poll.public ? 'published' : 'unpublished'}" }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
    #flash[:notice] = "ended poll"
  end
    

end

app/helpers/polls_helper.rb
module PollsHelper
  def format_poll_type(type)
    case type
    when 'OPEN'
      return 'Open Answer'
    when 'MULTI'
      return 'Multiple Choice'
    end
    return ''
  end

  def sparkline(data, width=100, height=40, style='', _class='')
    return image_tag(Gchart.sparkline(:data=>data, :width=>width, :height=>height, :bg=>'00000000'), :style=>style, :class=>_class)
  end

  def format_poll_running(poll)
    return poll.running? ? "Live" : "Ended"
  end

  def format_poll_date(date)
    return date.strftime("%m/%d/%y")
  end

  def format_poll_ran_dates(poll)
    if poll.running?
      str = "Running #{time_ago_in_words(poll.start_date, include_seconds = false)} &bull; #{format_poll_date(poll.start_date)} &ndash; now"
    else
      str = "Ran #{distance_of_time_in_words(poll.end_date, poll.start_date)} &bull; #{format_poll_date(poll.start_date)} &ndash;  #{format_poll_date(poll.end_date)}"
    end
    return str
    #str = poll.running? ? "Running " : "Ran "
    #<%= poll.start_date.strftime("%m/%d/%y %I:%M %p")%><

    #             %= time_ago_in_words(poll.start_date, include_seconds = false) %> ago</td>
  end

  #formats seconds into days, minutes, etc
  def format_time(secs)
    if secs < 60
      return pluralize(secs.round, 'second')
    elsif secs < 60 * 60
      return pluralize((secs/60).round, 'minute')
    elsif secs < 60 * 60 * 24
      return pluralize((secs/60/60).round, 'hour')
    else
      return pluralize((secs/60/60/24).round, 'day')
    end
  end

  # takes in an array of word, count  array pairs and prints them out in html
  # => [["Paris", 12], ["Wal-mart", 12], ["I", 12], ["buy", 12], ["groceries", 12], ["in", 12], ["Stater", 8], ["Acme", 8], ["or", 8], ["Supreme", 8], ["CVS", 8], ["bros", 8], ["Walgreens", 5]] 
  def html_histogram(histogram)
    result = '' 
    if histogram
      result << "<table>"
      histogram.slice(0,7).each do |h|
        result << "<tr style='font-size:#{0.8+h[1]/20.0}em' class='histogram-pair'><td class='histogram-word'>#{h[0]}</td><td class='histogram-count'>#{h[1]}</td><td style='width:200px;'><div class='histogram-graph' style='width:#{h[1]*8}px;'>&nbsp;</div></td></tr>\n"
      end
      result << "</table>"
    end
    return raw result
  end
end

app/views/polls/_follow_up_fields.html.erb
<div class="nested-fields followup-field not-counted">
  <!--<div class="msg-preview"></div> -->
  <%= f.input :text, :as => :text, :label => 'Followup', :label_html => { :class => "label-bold" }, :input_html => { :class => "input-xlarge followup-input", :rows => 2 }, :hint => (link_to_remove_association '×', f, :class => 'close remove-follow-up') %>
  <div class="msg-count msg-count-followup"></div>
  <%= f.input :question_type, :label => "Format" , :collection=>[['Open','OPEN'],['Multiple Choice','MULTI'],['Yes / No', 'YN']], :include_blank => false, :disabled => (!@poll.new_record? and !@poll.responses.empty?), :input_html => { :class => "followup-type span2" }%>

  <div class="options">	
    <%= f.simple_fields_for :follow_up_options do |follow_up_option| %>
      <%= render 'follow_up_option_fields', :f => follow_up_option %>
    <% end %>

    <%= link_to_add_association 'Add followup option', f, :follow_up_options, :"data-association-insertion-method" => :append, :class => "controls add-followup-option-button" %>
  </div>
</div>

app/views/polls/_follow_up_option_fields.html.erb
<div class="nested-fields followup-option-field">
  <fieldset>
    <%= f.input :text, :label => false, :input_html => {:class => 'followup-option-text'}, :hint => (link_to_remove_association "×", f , :class => 'close remove-follow-up-option') %>
    <%= f.input :value, :as => :hidden, :label => 'Option value', :input_html => {:class => 'followup-option-value'} %>
  </fieldset>
</div>

app/views/polls/_form.html.erb
<script>
  function togglePhone(){
    var phoneInput = $('#poll_phone')
    phoneInput.prop('disabled', function(i,v){ return !v; });
    phoneInput.toggleClass('disabled');
  }
  <% unless @poll.new_record? %>
    var initEditing = true;
  <% end %>
</script>

<% content_for :javascript_includes do %>
  <%= javascript_include_tag "form-filling.js" %>
<% end %>
<%= simple_form_for @poll, :html => { :class => "form-horizontal"} do |f| %>

  <div class="row">
    <div class="span8">

      <% if (!@poll.new_record? and !@poll.responses.empty?) %>
        <div class="alert" style="margin-top: 0;">
          <a class="close" data-dismiss="alert" href="#">×</a>
          <strong>Warning!</strong>
          You already have responses for this poll, so you can't change an existing question's type or remove options unless you <%= link_to 'clear all responses', clear_responses_poll_path(@poll), :confirm => 'Are you sure?!', :method => :put %> first. You can still make most other edits, though.
        </div>
      <% end %>

      <h3>Questions</h3>
      <div class="item-container dragenabled">
        <%= f.simple_fields_for :questions do |question| %>
          <%= render 'question_fields', :f => question %>
        <% end %>

        <div class="form-actions">
          <%= link_to_add_association '+ Add Question', f, :questions, :class => "btn btn-large", :id => 'add_qn_button' %>
          <!-- Javascript to "click" the add question button (hackaround!) -->
        </div>
      </div>


      <h3>Settings</h3>
      <div class="item-container">

        <div class= "nested-fields spacing">
          <div class = "confirmation">
            <%= f.input :confirmation, :placeholder => "Thanks for your feedback! More info: [your org's website]", :input_html => {:rows => 3, :cols => 20 }, :hint => "<div class='msg-count msg-count-confirmation'></div>" %>
          </div>
          <%= f.input :title, :label => "Nickname", :hint => "Short, descriptive title for reporting. <br/> Example: \"15 responses this week to your poll on ________.\"" %>

          <div class="field" style="display:none;">
            <%= f.label :start_date %>
            <%= f.datetime_select :start_date %>
          </div>

          <div class="field">
            <fieldset>
              <div class="control-group">
                  <%= f.label :end_date, :class => "control-label" %>
                <div class="controls">
                  <%= f.date_select(:end_date, {:use_short_month => 1, :order => [:month, :day, :year]}, {:class => "span1"}) %>
                </div>
              </div>
              <% if params[:group] %>
                <%= f.input :group_ids, :label => "Group", :selected => params[:group], :collection => @groups, :include_blank => false, :input_html => {:multiple => false} %>
              <% else %>
                <%= f.input :group_ids, :label => "Group", :collection => @groups, :include_blank => false, :input_html => {:multiple => false} %>
              <% end %>
              <%= f.input :phone, :placeholder => "Will be auto assigned", :hint => "<input type='checkbox' name='auto_assign' onClick='togglePhone()' class='alignbox'></input> Override?", :disabled=>true %>
              <%= f.input :public, :label => "Publish results?", :as => :radio, :collection => [["No", false],["Yes, let anyone view results", true]] %>
              <%=  %>
          </fieldset>
          </div>
        </div>

        <div class="form-actions">
          <%= f.button :submit, :class => 'btn btn-large btn-primary', :id => 'poll-form-submit' %>
          <%= link_to 'Cancel', @poll, :class => 'btn btn-large' %>
        </div>
      </div>
    </div>

    <div class="span4" id="form_sidebar">
      <!-- TODO: refactor so that Five Tips is a partial called from both this page and getstarted -->
      <div class="sideblock">
        <h3>Five Tips for Great Surveys</h3>
        <ol class="copylist">
          <li>
            <b>Start by getting people opinionated enough to engage</b>
            <br>Yes/No and Multiple Choice questions are low pressure ways to get people hooked. When using an Open Ended as your first question, be specific (i.e. "What was the last time...") to break the ice.</li>
          <li>
            <b>Ask questions that give the data you need</b>
            <br>If you want to know whether people support a new construction project, ask a Yes/No question. If you want to know why, an open ended question works best.
          </li>
          <li>
            <b>Consider adding 1 open-ended question</b>
            <br>Sometimes the best feedback comes after the formal survey is over. If you start with Yes/No or Multiple Choice questions, you can follow with an open question such as “Why or why not?” or “Anything else to add?”
          </li>
          <li>
            <b>Limit your survey to 3-5 questions</b>
            <br>People are taking time to respond to your survey and using up their text limits (or paying per message) to text in their responses. Keeping your survey to 3-5 questions shows you respect these commitments while maintaining room to get the data you need.
          </li>
          <li>
            <b>When using a survey for instant feedback, create it beforehand.</b>
            <br>When you create a new survey, the phone number takes 2-5 minutes to go live. All other edits go live immediately. For example, create a survey for a city council meeting in the afternoon to ensure that it's live for the evening meeting.
          </li>
        </ol>
      </div>
      <div class="sideblock blockmiddle">
        <p>For more tips &amp; examples, check out:</p>
        <h3><a href="../../getstarted">Getting Started With Textizen ›</a></h3>
      </div>

    </div>
  </div>
<% end %>

app/views/polls/_header.html.erb
<div class="row header">
    <div class="span8"><a href="/polls"><img src="/assets/logo.png"></a></div>
    <div class="span4 login"><%= link_to "Logout", destroy_user_session_path, :method=>:delete %></div>
</div>

app/views/polls/_histogram.html.erb
<% unless question.nil? %>
  <% if question.responses.empty? %>
    No responses...
  <% else %>
    <% num_entries ||= 7 %>
    <table>
      <% question.response_histogram.slice(0, num_entries).each do |h| %>
        <!--<tr style='font-size:<%= 0.8+h[1]/20.0 %>em' class='histogram-pair'>-->
        <tr class='histogram-pair'>
          <td class='histogram-word' nowrap="nowrap">
            <% harr = h[0].split("\s") %>
            <% harr[0].capitalize! %>
            <%= h[0] = harr.join(' ') %>
          </td>
          <td class='histogram-count'>
            <%= h[1] %>
          </td>
          <td style='width:200px'>
            <div class='histogram-graph' style='width: <%= (h[1].to_f) / (@poll.responses.count) * 200 %>px;'>&nbsp;</div>
          </td>
        </tr>
      <% end %>
    </table>
  <% end %> 
<% end %>

app/views/polls/index.html.erb
<div class="row">
  <div class="span12 main">
    <% if current_user.visible_polls.empty? and current_user.groups.empty? %>
        <div class="caption nopolls">No groups yet. Get invited to a group, or <%= link_to 'create one now', new_group_path %>!</div>
    <% end %>
    <% @groups.each do |group| %>
      <div class="pollsgroup">
          <div class="grouptitle">
            <%= link_to group.name, edit_group_path(group) %>
          </div>
          <div class="groupnewpoll">
          </div>
          <% if group.polls.empty? %>
            <div class="caption nopolls">No polls in this group yet.</div>
          <% end %>
          <table class="table pollslist">
            <% group.polls.each_with_index do |poll, i| %>
              <tr onClick="window.location.href='<%= poll_path(poll) %>'">
                <td class="number"><%= i+1 %></td>

                <td class="polltext">
                  <%= poll.questions.first.text if poll.questions.length > 0 %>
                </td>

                <td>
                  <div class="dashboardresponsecount"><%= poll.questions.empty? ? '0' : poll.questions.first.responses.count %></div>
                  <div class="caption">responses</div>
                </td>

                <td><%= sparkline poll.time_series %><br><span class="caption">latest <%= format_time poll.time_since_last_response %> ago</span></td>

                <td><%= format_poll_running(poll)%><br/><%= raw format_poll_ran_dates(poll)%></td>

                <td id="pollactions">
                  <%= link_to(raw('<i class="icon-th-large"></i>Show'), poll) %>
                  &nbsp;&nbsp;&nbsp;&nbsp;
                  <span class="poll-edit"><%= link_to(raw('<i class="icon-pencil"></i>Edit'), edit_poll_path(poll)) %></span>
                </td>

              </tr>
            <% end %>
          </table>
            <%= link_to raw("<i class='icon-plus'></i>New Poll in #{group.name}"), new_poll_path(:group => group.id), :class => "btn btn-large"%>
          <br />
      </div>
    <% end %>

    <% if !(current_user.created_polls - current_user.polls).empty? %>
      <div class="grouptitle">
        Orphaned Polls :(
      </div>
      <table class="table pollslist">
        <% (current_user.created_polls - current_user.polls).each_with_index do |poll, i| %>
          <tr onClick="window.location.href='<%= poll_path(poll) %>'">
            <td class="number"><%= i+1 %></td>

            <td class="polltext">
              <%= poll.questions.first.text if poll.questions.length > 0 %>
            </td>

            <td>
              <div class="dashboardresponsecount"><%= poll.questions.empty? ? '0' : poll.questions.first.responses.count %></div>
              <div class="caption">responses</div>
            </td>

            <td><%= sparkline poll.time_series %><br><span class="caption">latest <%= format_time poll.time_since_last_response %> ago</span></td>

            <td>Live <%= poll.start_date.strftime("%m/%d/%y %I:%M %p")%><br><%= time_ago_in_words(poll.start_date, include_seconds = false) %> ago</td>

            <td id="pollactions">
              <%= link_to(raw('<i class="icon-th-large"></i>Show'), poll) %>
              &nbsp;&nbsp;&nbsp;&nbsp;
              <span class="poll-edit"><%= link_to(raw('<i class="icon-pencil"></i>Edit'), edit_poll_path(poll)) %></span>
            </td>

          </tr>
        <% end %>
      </table>
    <% end %>
    <% if !(current_user.visible_polls - current_user.created_polls - current_user.polls).empty? %> <!-- for superadmins -->
      <div class="grouptitle">
        All Polls Without a Group
      </div>
      <table class="table pollslist">
        <% (current_user.visible_polls - current_user.created_polls - current_user.polls).each_with_index do |poll, i| %>
          <tr onClick="window.location.href='<%= poll_path(poll) %>'">
            <td class="number"><%= i+1 %></td>

            <td class="polltext">
              <%= poll.questions.first.text if poll.questions.length > 0 %>
            </td>

            <td>
              <div class="dashboardresponsecount"><%= poll.questions.empty? ? '0' : poll.questions.first.responses.count %></div>
              <div class="caption">responses</div>
            </td>

            <td><%= sparkline poll.time_series %><br><span class="caption">latest <%= format_time poll.time_since_last_response %> ago</span></td>

            <td>Live <%= poll.start_date.strftime("%m/%d/%y %I:%M %p")%><br><%= time_ago_in_words(poll.start_date, include_seconds = false) %> ago
            </td>

            <td id="pollactions">
              <%= link_to(raw('<i class="icon-th-large"></i>Show'), poll) %>
              &nbsp;&nbsp;&nbsp;&nbsp;
              <span class="poll-edit"><%= link_to(raw('<i class="icon-pencil"></i>Edit'), edit_poll_path(poll)) %></span>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
    <br />
  </div>
</div>

app/views/polls/new.html.erb
<div class="row">
  <div class="span12 main">
    <div class="grouptitle">New Poll</div>
    <%= render 'form' %>
  </div>
</div>

app/views/polls/show.html.erb
<% choices = {} %>


<% if can? :manage, @poll and @poll.public %>
  <div class="alert">
    This poll is <strong>public</strong>. Here's the URL to share results: <%= link_to poll_path(@poll, :only_path => false), poll_path(@poll) %>
    <a id="twitter-share-poll" href="https://twitter.com/share" class="twitter-share-button" data-related="Textizen" data-dnt="true" data-text="<%="Just published our @Textizen poll on #{@poll.title}. See results as they come in!"%>">Tweet this poll!</a>
  </div>
<% end %>

<div class="row">
  <div class="span12 main">
    <div class="grouptitle"><%= @poll.groups.empty? ? "Polls" : @poll.groups.first.name %> &rsaquo; <%= @poll.title %></div>
    <!--<p id="notice"><%= notice %></p>-->
  </div>
</div>
<div class="row">
  <div class="span6">
    <ol>
      <% @poll.questions.in_order.each do |q| %>
        <li class="question"><span class="qtext"><%= q.text %></span> <span class="qtype">(<%= q.question_type %>)</span></li>
        <% unless q.options.empty? %>
          <ul class="optionslist">
            <% q.options.each do |o| %>
              <li><span class="optionvalue"><%= o.value %>:</span> <%= o.text %></li>
              <% o.follow_up.each do |fup| %>
                <ul class="optionslist questionindent">
                  <li class="question"><span class="qtext"><%= fup.text %></span> <span class="qtype">(<%= fup.question_type %>)</span></li>
                  <% unless fup.options.empty? %>
                    <ul class="optionslist">
                      <% fup.options.each do |o| %>
                        <li><span class="optionvalue"><%= o.value %>:</span> <%= o.text %></li>
                      <% end %>
                    </ul>
                  <% end %>
                </ul>
              <% end %>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    </ol>
  </div>

  <div class="span3">
    <div class="counterdash">
      <div class="responsecount"><%= @poll.questions.first.responses.count %></div>
      <br>
      <span class="caption">responses</span>
      <br>
      <!--img src="http://chart.apis.google.com/chart?chf=a,s,000000&chs=100x40&cht=ls&chd=s:degddgjmqxuurruxwrro&chls=1&chf=bg,s,65432100" width="100" height="40" alt="" /-->
      <%= sparkline @poll.time_series %>
      <br>
      <span class="caption">latest about <%= format_time @poll.time_since_last_response %> ago</span>
    </div>
  </div>

  <div class="span3">
    <div class="settings">
      <div class="caption">Assigned phone</div>
      <div class="settingstext"><%= number_to_phone(@poll.phone, :area_code => true)[1..-1] %></div>

      <div class="caption">Start date</div>
      <div class="settingstext"><%= @poll.start_date.strftime("%m/%d/%Y at %I:%M%p") %></div>

      <div class="caption">Status</div>
      <div class="settingstext"><%= @poll.running? ? 'Running' : 'Ended' %></div>

      <% if can? :manage, @poll %>
        <div class="caption">Results public?</div>
        <div class="settingstext"><%= @poll.public ? "Yes" : "No" %></div>

        <div class="btn-toolbar btngroup edit-poll">
          <div class="btn-group">
            <%= link_to 'Edit', edit_poll_path(@poll), :class => "btn btn-info", :id => "edit-button" %>
          </div>

          <% if @poll.running? %>
            <div class="btn-group">
              <a class="btn dropdown-toggle" data-toggle="dropdown" href="#" id="danger-dropdown">
                Dangerous
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'End poll', end_poll_path(@poll), :confirm => 'Are you sure?', :method => :put %></li>
                <li class="divider"></li>
                <li><%= link_to 'Clear all responses', clear_responses_poll_path(@poll), :confirm => 'Are you sure?!', :method => :put %></li>
                <li><%= link_to 'Trash poll', @poll, confirm: 'Are you sure?', method: :delete %></li>
              </ul>
            </div>
          <% else %>
            <div class="btn-group"><%= link_to 'Trash poll', @poll, confirm: 'Are you sure?', method: :delete, :class => "btn" %></div>
          <% end %>

          <!--&nbsp;<%= link_to 'Trash', @poll, confirm: 'Are you sure?', method: :delete %>-->
        </div>
      <% end %>

    </div>
  </div>
</div>

<div class="row">
  <div class="span12">
    <div class="summaryviz">
      <div class="caption">Frequently mentioned words</div>
      <%= render "histograms", :poll=>@poll %>
    </div>
  </div>
</div>



<div class="row">
  <div class="span12 horiz"></div>
</div>

<div class="row">
  <div class="span12">
    <div class="download">
      <%= link_to "→ Download CSV", request.parameters.merge({:format => :csv}), :id => 'download-csv-link'%>
    </div>
    <h3>Responses</h3>
    <table class="table">
      <tr>
        <th>
          <th>Timestamp</th>
          <% @poll.questions_all.each do |q| %>
            <th><%= q.text %></th>
          <% end %>
          <% if can? :read_full, @poll %>
            <th>Phone number</th>
          <% end %>
        </tr>
        <% @poll.responses_flat.each_with_index do |resp, i| %>
          <tr>
            <td><%= i+1 %></td>
            <td><%= resp[:first_response_created].strftime("%m/%d/%Y at %I:%M%p")%></td>
            <% @poll.questions_all.each do |q| %>
              <td>
                <span class="optionvalue">
                  <% if can? :read_full, @poll %>
                    <%= resp[:texts][q.id] %></span><%= q.get_matching_option(resp[:texts][q.id])? ": #{q.get_matching_option(resp[:texts][q.id])}" : '' unless q.options.empty? %>
                  <% else %>
                    <%= resp[:texts][q.id].nil? ? '' : resp[:texts][q.id].gsub(Question::POISON_WORDS_REGEX, '---') %></span><%= q.get_matching_option(resp[:texts][q.id])? ": #{q.get_matching_option(resp[:texts][q.id])}" : '' unless q.options.empty? %>
                  <% end %>
              </td>
            <% end %>
            <% if can? :read_full, @poll %>
              <td nowrap="nowrap"><%= number_to_phone(resp[:from], :area_code => true)[1..9] %>-XXXX</td>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
</div>